module.exports = `
  schema {
    query: Query
  }

  type Query{
    page: [page]
  }

  type page implements Node {
      id: String
      uuid: String
      title: String
      slug: String
      last_published_at: Date
      hostname: String
      type: String
      branding: branding
      contact_email: String
      program_documents: program_documents
      external_program_website: external_program_website
  }

  type branding {
    cover_image: String
    banner_border_color: String
    texture_image: String
    organization_logo: organization_logo
  }

  type organization_logo {
    url: String
    alt: String
  }

  type program_documents {
    header: String
    display: Boolean
    documents: [document]
  }

  type external_program_website {
    header: String,
    link: link,
    display: Boolean,
    description: String,
},

  type document {
    display_text: String
    document: String
    url: String
  }

  type link {
    display_text: String,
    url: String,
  },
`;
